In [ ]:
import pandas as pd
import numpy as np

data = {
    "Student Name": ["Aditi", "Rahul", "Priya", "Aman", "Aditi", "Neha"],
    "Age": ["22", "21", "23", "22", "22", "Twenty"],
    "Join Date": ["2026-01-10", "2026-02-15", "2026-03-20", "2026-04-05", "2026-01-10", "2026-05-12"],
    "Marks": [85, 78, np.nan, 91, 85, 88],
    "Department": ["Data Science", "data science", "AI & ML", "AI & ML", "Data Science", None]
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

Original Dataset:

  Student Name     Age   Join Date  Marks    Department
0        Aditi      22  2026-01-10   85.0  Data Science
1        Rahul      21  2026-02-15   78.0  data science
2        Priya      23  2026-03-20    NaN       AI & ML
3         Aman      22  2026-04-05   91.0       AI & ML
4        Aditi      22  2026-01-10   85.0  Data Science
5         Neha  Twenty  2026-05-12   88.0          None

In [ ]:


print("Dataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student Name  6 non-null      object
 1   Age           6 non-null      object
 2   Join Date     6 non-null      object
 3   Marks         5 non-null      float64
 4   Department    5 non-null      object
dtypes: float64(1), object(4)
memory usage: 372.0+ bytes

Missing Values:
Student Name    0
Age             0
Join Date       0
Marks           1
Department      1
dtype: int64

Duplicate Rows:
1

Data Types:
Student Name     object
Age              object
Join Date        object
Marks           float64
Department       object
dtype: object

In [ ]:
# Check missing values before cleaning
print("Missing values before cleaning:")
print(df.isnull().sum())

# Fill missing Marks with the average marks
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

# Fill missing Department with "Unknown"
df["Department"] = df["Department"].fillna("Unknown")

print("\nMissing values after cleaning:")
print(df.isnull().sum())

print("\nUpdated Dataset:")
display(df)

Missing values before cleaning:
Student Name    0
Age             0
Join Date       0
Marks           1
Department      1
dtype: int64

Missing values after cleaning:
Student Name    0
Age             0
Join Date       0
Marks           0
Department      0
dtype: int64

Updated Dataset:

  Student Name     Age   Join Date  Marks    Department
0        Aditi      22  2026-01-10   85.0  Data Science
1        Rahul      21  2026-02-15   78.0  data science
2        Priya      23  2026-03-20   85.4       AI & ML
3         Aman      22  2026-04-05   91.0       AI & ML
4        Aditi      22  2026-01-10   85.0  Data Science
5         Neha  Twenty  2026-05-12   88.0       Unknown

In [ ]:
# Convert Age from text to numeric
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

# Convert Join Date from text to datetime
df["Join Date"] = pd.to_datetime(df["Join Date"], errors="coerce")

print("Updated Data Types:")
print(df.dtypes)

print("\nUpdated Dataset:")
display(df)

Updated Data Types:
Student Name            object
Age                    float64
Join Date       datetime64[ns]
Marks                  float64
Department              object
dtype: object

Updated Dataset:

  Student Name   Age  Join Date  Marks    Department
0        Aditi  22.0 2026-01-10   85.0  Data Science
1        Rahul  21.0 2026-02-15   78.0  data science
2        Priya  23.0 2026-03-20   85.4       AI & ML
3         Aman  22.0 2026-04-05   91.0       AI & ML
4        Aditi  22.0 2026-01-10   85.0  Data Science
5         Neha   NaN 2026-05-12   88.0       Unknown

In [ ]:
# Handle invalid/missing Age values
df["Age"] = df["Age"].fillna(df["Age"].median())

# Standardize Department names
df["Department"] = df["Department"].str.strip().str.title()

print("Dataset after fixing Age and Department:")
display(df)

Dataset after fixing Age and Department:

  Student Name   Age  Join Date  Marks    Department
0        Aditi  22.0 2026-01-10   85.0  Data Science
1        Rahul  21.0 2026-02-15   78.0  Data Science
2        Priya  23.0 2026-03-20   85.4       Ai & Ml
3         Aman  22.0 2026-04-05   91.0       Ai & Ml
4        Aditi  22.0 2026-01-10   85.0  Data Science
5         Neha  22.0 2026-05-12   88.0       Unknown

In [ ]:
# Check duplicate rows before removing them
print("Duplicate rows before cleaning:", df.duplicated().sum())

# Remove duplicate rows
df = df.drop_duplicates()

print("Duplicate rows after cleaning:", df.duplicated().sum())

print("\nDataset after removing duplicates:")
display(df)

Duplicate rows before cleaning: 1
Duplicate rows after cleaning: 0

Dataset after removing duplicates:

  Student Name   Age  Join Date  Marks    Department
0        Aditi  22.0 2026-01-10   85.0  Data Science
1        Rahul  21.0 2026-02-15   78.0  Data Science
2        Priya  23.0 2026-03-20   85.4       Ai & Ml
3         Aman  22.0 2026-04-05   91.0       Ai & Ml
5         Neha  22.0 2026-05-12   88.0       Unknown

In [ ]:
# Standardize column names

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("&", "and")
)

print("Standardized Column Names:")
print(df.columns.tolist())

print("\nFinal Dataset:")
display(df)

Standardized Column Names:
['student_name', 'age', 'join_date', 'marks', 'department']

Final Dataset:

  student_name   age  join_date  marks    department
0        Aditi  22.0 2026-01-10   85.0  Data Science
1        Rahul  21.0 2026-02-15   78.0  Data Science
2        Priya  23.0 2026-03-20   85.4       Ai & Ml
3         Aman  22.0 2026-04-05   91.0       Ai & Ml
5         Neha  22.0 2026-05-12   88.0       Unknown

In [ ]:
# Save the cleaned dataset

output_file = "cleaned_dataset.csv"

df.to_csv(output_file, index=False)

print("Cleaned dataset saved successfully!")
print("File name:", output_file)

# Display the final cleaned dataset
display(df)

Cleaned dataset saved successfully!
File name: cleaned_dataset.csv

  student_name   age  join_date  marks    department
0        Aditi  22.0 2026-01-10   85.0  Data Science
1        Rahul  21.0 2026-02-15   78.0  Data Science
2        Priya  23.0 2026-03-20   85.4       Ai & Ml
3         Aman  22.0 2026-04-05   91.0       Ai & Ml
5         Neha  22.0 2026-05-12   88.0       Unknown

In [ ]:


import os

if os.path.exists("cleaned_dataset.csv"):
    print("✅ cleaned_dataset.csv is ready")
    print("Number of rows:", len(df))
    print("Number of columns:", len(df.columns))
else:
    print("❌ File was not created")

✅ cleaned_dataset.csv is ready
Number of rows: 5
Number of columns: 5

In [ ]:
# Create a cleaning log

cleaning_log = {
    "Step": [
        "Missing Values",
        "Age Data Type",
        "Date Parsing",
        "Invalid Age",
        "Department Standardization",
        "Duplicate Removal",
        "Column Name Standardization"
    ],

    "Action Taken": [
        "Filled missing Marks with mean and Department with Unknown",
        "Converted Age from text to numeric",
        "Converted Join Date to datetime format",
        "Replaced invalid Age value with median Age",
        "Standardized Department capitalization",
        "Removed duplicate rows",
        "Converted column names to lowercase with underscores"
    ]
}

log_df = pd.DataFrame(cleaning_log)

print("Cleaning Log:")
display(log_df)

Cleaning Log:

,Step,Action Taken
0,Missing Values,Filled missing Marks with mean and Department ...
1,Age Data Type,Converted Age from text to numeric
2,Date Parsing,Converted Join Date to datetime format
3,Invalid Age,Replaced invalid Age value with median Age
4,Department Standardization,Standardized Department capitalization
5,Duplicate Removal,Removed duplicate rows
6,Column Name Standardization,Converted column names to lowercase with under...

In [ ]:
# Save cleaning log as CSV

log_df.to_csv("cleaning_log.csv", index=False)

print("✅ Cleaning log saved as cleaning_log.csv")

✅ Cleaning log saved as cleaning_log.csv

In [ ]:
# Final quality check

print("===== FINAL DATA QUALITY CHECK =====")

# Check missing values
print("\n1. Missing Values:")
print(df.isnull().sum())

# Check duplicate rows
print("\n2. Duplicate Rows:")
print(df.duplicated().sum())

# Check data types
print("\n3. Data Types:")
print(df.dtypes)

# Check column names
print("\n4. Column Names:")
print(df.columns.tolist())

# Display final dataset
print("\n5. Final Cleaned Dataset:")
display(df)

===== FINAL DATA QUALITY CHECK =====

1. Missing Values:
student_name    0
age             0
join_date       0
marks           0
department      0
dtype: int64

2. Duplicate Rows:
0

3. Data Types:
student_name            object
age                    float64
join_date       datetime64[ns]
marks                  float64
department              object
dtype: object

4. Column Names:
['student_name', 'age', 'join_date', 'marks', 'department']

5. Final Cleaned Dataset:

  student_name   age  join_date  marks    department
0        Aditi  22.0 2026-01-10   85.0  Data Science
1        Rahul  21.0 2026-02-15   78.0  Data Science
2        Priya  23.0 2026-03-20   85.4       Ai & Ml
3         Aman  22.0 2026-04-05   91.0       Ai & Ml
5         Neha  22.0 2026-05-12   88.0       Unknown

In [ ]:
# Create final cleaning summary

summary = {
    "Original Rows": 6,
    "Final Rows": len(df),
    "Original Columns": 5,
    "Final Columns": len(df.columns),
    "Missing Values Remaining": int(df.isnull().sum().sum()),
    "Duplicate Rows Remaining": int(df.duplicated().sum())
}

summary_df = pd.DataFrame(
    summary.items(),
    columns=["Metric", "Value"]
)

print("===== CLEANING SUMMARY =====")
display(summary_df)

===== CLEANING SUMMARY =====

                     Metric  Value
0             Original Rows      6
1                Final Rows      5
2          Original Columns      5
3             Final Columns      5
4  Missing Values Remaining      0
5  Duplicate Rows Remaining      0

In [ ]:
summary_df.to_csv("cleaning_summary.csv", index=False)

print("✅ Cleaning summary saved as cleaning_summary.csv")

✅ Cleaning summary saved as cleaning_summary.csv

In [ ]:
df.to_csv("cleaned_dataset.csv", index=False)

In [ ]:
log_df.to_csv("cleaning_log.csv", index=False)

In [ ]:
summary_df.to_csv("cleaning_summary.csv", index=False)

In [ ]:
from google.colab import files

# Download cleaned dataset
files.download("cleaned_dataset.csv")

# Download cleaning log
files.download("cleaning_log.csv")

# Download cleaning summary
files.download("cleaning_summary.csv")